export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const USER_LIST_FETCH_SUCCESS = 'USER_LIST_FETCH_SUCCESS'

export const SELECT_PROJECT = 'SELECT_PROJECT'

export const PROJECT_LIST_FETCH_REQUEST = 'PROJECT_LIST_FETCH_REQUEST'
export const PROJECT_LIST_FETCH_SUCCESS = 'PROJECT_LIST_FETCH_SUCCESS'
export const PROJECT_LIST_FETCH_FAILURE = 'PROJECT_LIST_FETCH_FAILURE'

export const SAVE_PROJECT_REQUEST = 'SAVE_PROJECT_REQUEST'
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS'
export const SAVE_PROJECT_FAILURE = 'SAVE_PROJECT_FAILURE'

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'

export const PROJECT_BOARD_FETCH_REQUEST = 'PROJECT_BOARD_FETCH_REQUEST'
export const PROJECT_BOARD_FETCH_SUCCESS = 'PROJECT_BOARD_FETCH_SUCCESS'
export const PROJECT_BOARD_FETCH_FAILURE = 'PROJECT_BOARD_FETCH_FAILURE'

export const SAVE_TASK_REQUEST = 'SAVE_TASK_REQUEST'
export const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS'
export const SAVE_TASK_FAILURE = 'SAVE_TASK_FAILURE'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'
